"""empty message"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '34af88038b57'
down_revision = '20240915_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'metadata')
    # ### end Alembic commands ###
